version: '3.8'

services:
  # 1. Banco de Dados (PostgreSQL)
  db:
    image: postgres:16-alpine
    container_name: locplus-db
    restart: always
    environment:
      POSTGRES_USER: locplus_admin
      POSTGRES_PASSWORD: locplus_senha_segura # Em produção, usaremos variáveis de ambiente (.env)
      POSTGRES_DB: locplus_db
    ports:
      - "5432:5432"
    volumes:
      - locplus_postgres_data:/var/lib/postgresql/data

  # 2. Armazenamento de Arquivos/Vistorias (MinIO - Alternativa local ao AWS S3)
  minio:
    image: minio/minio
    container_name: locplus-minio
    restart: always
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_senha_segura
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # Porta da API (onde nosso backend em Python vai se conectar)
      - "9001:9001" # Porta do Painel Visual (onde você pode acessar pelo navegador)
    volumes:
      - locplus_minio_data:/data

  # 3. Gerenciador Visual do Banco de Dados (Bônus para facilitar o desenvolvimento)
  adminer:
    image: adminer
    container_name: locplus-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

# Volumes nomeados garantem que você não perca os dados se o Docker for reiniciado
volumes:
  locplus_postgres_data:
  locplus_minio_data: