"""Migracao inicial limpa com seguranca

Revision ID: 442068486123
Revises: 
Create Date: 2026-03-25 02:43:00.618179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '442068486123'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('documento', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_documento'), 'clientes', ['documento'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_cnpj'), 'empresas', ['cnpj'], unique=True)
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('objetivo', sa.Enum('LOCADOR', 'LOCATARIO', name='objetivoconta'), nullable=False),
    sa.Column('tipo_entidade', sa.Enum('PF', 'PJ', name='tipoentidade'), nullable=False),
    sa.Column('nome_completo', sa.String(), nullable=False),
    sa.Column('documento', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('is_ativo', sa.Boolean(), nullable=True),
    sa.Column('is_verificado', sa.Boolean(), nullable=True),
    sa.Column('viu_guia_cadastro', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_documento'), 'usuarios', ['documento'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('apelido', sa.String(), nullable=False),
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('is_principal', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enderecos_id'), 'enderecos', ['id'], unique=False)
    op.create_table('equipamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('numero_serie_patrimonio', sa.String(), nullable=True),
    sa.Column('valor_base_locacao', sa.Float(), nullable=False),
    sa.Column('tipo_cobranca', sa.Enum('DIARIA', 'MENSAL', 'HORA', 'FRANQUIA', name='tipocobranca'), nullable=True),
    sa.Column('categoria', sa.Enum('LINHA_PESADA', 'LINHA_LEVE', 'VEICULOS', 'MENSALISTAS', 'DIVERSOS', name='categoriaequipamento'), nullable=True),
    sa.Column('quantidade_total', sa.Integer(), nullable=True),
    sa.Column('quantidade_disponivel', sa.Integer(), nullable=True),
    sa.Column('em_manutencao', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipamentos_id'), 'equipamentos', ['id'], unique=False)
    op.create_index(op.f('ix_equipamentos_nome'), 'equipamentos', ['nome'], unique=False)
    op.create_index(op.f('ix_equipamentos_numero_serie_patrimonio'), 'equipamentos', ['numero_serie_patrimonio'], unique=True)
    op.create_table('locacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim_prevista', sa.DateTime(), nullable=False),
    sa.Column('data_devolucao_real', sa.DateTime(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('endereco_entrega', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ORCAMENTO', 'AGUARDANDO_ENTREGA', 'EM_ANDAMENTO', 'FINALIZADO', 'CANCELADO', name='statuslocacao'), nullable=True),
    sa.Column('aluguel_representacao', sa.Boolean(), nullable=True),
    sa.Column('assinatura_digital_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locacoes_id'), 'locacoes', ['id'], unique=False)
    op.create_table('vistorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locacao_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTREGA', 'DEVOLUCAO', name='tipovistoria'), nullable=False),
    sa.Column('data_vistoria', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('assinatura_cliente_url', sa.String(), nullable=True),
    sa.Column('fotos_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['locacao_id'], ['locacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vistorias_id'), 'vistorias', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vistorias_id'), table_name='vistorias')
    op.drop_table('vistorias')
    op.drop_index(op.f('ix_locacoes_id'), table_name='locacoes')
    op.drop_table('locacoes')
    op.drop_index(op.f('ix_equipamentos_numero_serie_patrimonio'), table_name='equipamentos')
    op.drop_index(op.f('ix_equipamentos_nome'), table_name='equipamentos')
    op.drop_index(op.f('ix_equipamentos_id'), table_name='equipamentos')
    op.drop_table('equipamentos')
    op.drop_index(op.f('ix_enderecos_id'), table_name='enderecos')
    op.drop_table('enderecos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_documento'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_cnpj'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_documento'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
