"""implementacao_multi_tenant_saas

Revision ID: a8ebc5f3c5ea
Revises: bf1e7e2b3df9
Create Date: 2026-04-10 00:31:01.210770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8ebc5f3c5ea'
down_revision: Union[str, Sequence[str], None] = 'bf1e7e2b3df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('max_maquinas', sa.Integer(), nullable=False),
    sa.Column('max_usuarios', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_planos_id'), 'planos', ['id'], unique=False)
    op.create_table('assinaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('status_pagamento', sa.Enum('ATIVO', 'INATIVO', 'ATRASADO', name='statuspgto'), nullable=True),
    sa.Column('data_vencimento', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    op.create_index(op.f('ix_assinaturas_id'), 'assinaturas', ['id'], unique=False)
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('mensagem', sa.String(), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacoes_id'), 'notificacoes', ['id'], unique=False)
    op.drop_constraint(op.f('empresas_usuario_id_key'), 'empresas', type_='unique')
    op.drop_constraint(op.f('empresas_usuario_id_fkey'), 'empresas', type_='foreignkey')
    op.drop_column('empresas', 'usuario_id')
    op.add_column('usuarios', sa.Column('empresa_id', sa.Integer(), nullable=True))
    op.add_column('usuarios', sa.Column('role', sa.String(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'empresas', ['empresa_id'], ['id'])
    op.add_column('vistorias', sa.Column('empresa_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'vistorias', 'empresas', ['empresa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vistorias', type_='foreignkey')
    op.drop_column('vistorias', 'empresa_id')
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'role')
    op.drop_column('usuarios', 'empresa_id')
    op.add_column('empresas', sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('empresas_usuario_id_fkey'), 'empresas', 'usuarios', ['usuario_id'], ['id'])
    op.create_unique_constraint(op.f('empresas_usuario_id_key'), 'empresas', ['usuario_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_notificacoes_id'), table_name='notificacoes')
    op.drop_table('notificacoes')
    op.drop_index(op.f('ix_assinaturas_id'), table_name='assinaturas')
    op.drop_table('assinaturas')
    op.drop_index(op.f('ix_planos_id'), table_name='planos')
    op.drop_table('planos')
    # ### end Alembic commands ###
