"""migra_identidade_b2b_para_empresa

Revision ID: acf2bcd5d9f4
Revises: a8ebc5f3c5ea
Create Date: 2026-04-10 00:52:47.074121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf2bcd5d9f4'
down_revision: Union[str, Sequence[str], None] = 'a8ebc5f3c5ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('nome_fantasia', sa.String(), nullable=True))
    op.add_column('empresas', sa.Column('avaliacao', sa.Float(), nullable=True))
    op.drop_column('usuarios', 'razao_social')
    op.drop_column('usuarios', 'inscricao_estadual')
    op.drop_column('usuarios', 'nome_fantasia')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('nome_fantasia', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('usuarios', sa.Column('inscricao_estadual', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('usuarios', sa.Column('razao_social', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('empresas', 'avaliacao')
    op.drop_column('empresas', 'nome_fantasia')
    # ### end Alembic commands ###
