"""Criando tabela de locacoes e contratos

Revision ID: bbefe63bc284
Revises: f218d72edfdd
Create Date: 2026-03-23 01:38:18.207429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbefe63bc284'
down_revision: Union[str, Sequence[str], None] = 'f218d72edfdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim_prevista', sa.DateTime(), nullable=False),
    sa.Column('data_devolucao_real', sa.DateTime(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('endereco_entrega', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ORCAMENTO', 'AGUARDANDO_ENTREGA', 'EM_ANDAMENTO', 'FINALIZADO', 'CANCELADO', name='statuslocacao'), nullable=True),
    sa.Column('aluguel_representacao', sa.Boolean(), nullable=True),
    sa.Column('assinatura_digital_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locacoes_id'), 'locacoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locacoes_id'), table_name='locacoes')
    op.drop_table('locacoes')
    # ### end Alembic commands ###
