"""V2_Initial

Revision ID: bf1e7e2b3df9
Revises: 
Create Date: 2026-03-26 00:07:29.292578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1e7e2b3df9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('objetivo', sa.Enum('LOCADOR', 'LOCATARIO', name='objetivoconta'), nullable=False),
    sa.Column('tipo_entidade', sa.Enum('PF', 'PJ', name='tipoentidade'), nullable=False),
    sa.Column('nome_completo', sa.String(), nullable=False),
    sa.Column('documento', sa.String(), nullable=False),
    sa.Column('telefone_celular', sa.String(), nullable=True),
    sa.Column('telefone_fixo', sa.String(), nullable=True),
    sa.Column('rg', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('razao_social', sa.String(), nullable=True),
    sa.Column('nome_fantasia', sa.String(), nullable=True),
    sa.Column('inscricao_estadual', sa.String(), nullable=True),
    sa.Column('is_ativo', sa.Boolean(), nullable=True),
    sa.Column('is_verificado', sa.Boolean(), nullable=True),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True),
    sa.Column('aceitou_termos_uso', sa.Boolean(), nullable=True),
    sa.Column('viu_guia_cadastro', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_documento'), 'usuarios', ['documento'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('documentos_kyc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.Enum('CNH', 'RG', 'CONTRATO_SOCIAL', 'COMPROVANTE_RESIDENCIA', name='tipodocumento'), nullable=False),
    sa.Column('minio_s3_url', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADO', 'REJEITADO', name='statusverificacao'), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_kyc_id'), 'documentos_kyc', ['id'], unique=False)
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('SEDE', 'GALPAO', 'CANTEIRO_OBRAS', 'RESIDENCIAL', name='tipoendereco'), nullable=True),
    sa.Column('is_padrao', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enderecos_id'), 'enderecos', ['id'], unique=False)
    op.create_table('representacoes_b2b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('representante_usuario_id', sa.Integer(), nullable=False),
    sa.Column('cnpj_cliente_final', sa.String(), nullable=False),
    sa.Column('razao_social_cliente_final', sa.String(), nullable=False),
    sa.Column('comprovante_autorizacao_url', sa.String(), nullable=False),
    sa.Column('status_aprovacao', sa.Enum('ATIVA', 'PENDENTE', 'REVOGADA', name='statusrepresentacao'), nullable=True),
    sa.ForeignKeyConstraint(['representante_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_representacoes_b2b_cnpj_cliente_final'), 'representacoes_b2b', ['cnpj_cliente_final'], unique=False)
    op.create_index(op.f('ix_representacoes_b2b_id'), 'representacoes_b2b', ['id'], unique=False)
    op.create_table('equipamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('numero_serie_patrimonio', sa.String(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('ano_fabricacao', sa.Integer(), nullable=True),
    sa.Column('valor_diaria', sa.Float(), nullable=False),
    sa.Column('valor_semana', sa.Float(), nullable=True),
    sa.Column('valor_quinzena', sa.Float(), nullable=True),
    sa.Column('valor_mes', sa.Float(), nullable=True),
    sa.Column('foto_visao_geral', sa.String(), nullable=True),
    sa.Column('foto_painel', sa.String(), nullable=True),
    sa.Column('foto_motor', sa.String(), nullable=True),
    sa.Column('categoria', sa.Enum('LINHA_PESADA', 'LINHA_LEVE', 'VEICULOS', 'MENSALISTAS', 'DIVERSOS', name='categoriaequipamento'), nullable=True),
    sa.Column('quantidade_total', sa.Integer(), nullable=True),
    sa.Column('quantidade_disponivel', sa.Integer(), nullable=True),
    sa.Column('em_manutencao', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipamentos_id'), 'equipamentos', ['id'], unique=False)
    op.create_index(op.f('ix_equipamentos_nome'), 'equipamentos', ['nome'], unique=False)
    op.create_index(op.f('ix_equipamentos_numero_serie_patrimonio'), 'equipamentos', ['numero_serie_patrimonio'], unique=True)
    op.create_table('locacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim_prevista', sa.DateTime(), nullable=False),
    sa.Column('data_aceite_locatario', sa.DateTime(), nullable=True),
    sa.Column('data_devolucao_real', sa.DateTime(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('endereco_entrega', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ORCAMENTO', 'AGUARDANDO_ENTREGA', 'EM_ANDAMENTO', 'CONTESTACAO', 'MAQUINA_PARADA', 'FINALIZADO', 'CANCELADO', name='statuslocacao'), nullable=True),
    sa.Column('aluguel_representacao', sa.Boolean(), nullable=True),
    sa.Column('assinatura_digital_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locacoes_id'), 'locacoes', ['id'], unique=False)
    op.create_table('vistorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locacao_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTREGA', 'DEVOLUCAO', name='tipovistoria'), nullable=False),
    sa.Column('data_vistoria', sa.DateTime(), nullable=True),
    sa.Column('horimetro_odometro', sa.Float(), nullable=True),
    sa.Column('nivel_combustivel', sa.String(), nullable=True),
    sa.Column('check_pneus', sa.Boolean(), nullable=True),
    sa.Column('check_vidros', sa.Boolean(), nullable=True),
    sa.Column('check_lataria', sa.Boolean(), nullable=True),
    sa.Column('check_painel', sa.Boolean(), nullable=True),
    sa.Column('check_hidraulica', sa.Boolean(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('assinatura_cliente_url', sa.String(), nullable=True),
    sa.Column('fotos_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['locacao_id'], ['locacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vistorias_id'), 'vistorias', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vistorias_id'), table_name='vistorias')
    op.drop_table('vistorias')
    op.drop_index(op.f('ix_locacoes_id'), table_name='locacoes')
    op.drop_table('locacoes')
    op.drop_index(op.f('ix_equipamentos_numero_serie_patrimonio'), table_name='equipamentos')
    op.drop_index(op.f('ix_equipamentos_nome'), table_name='equipamentos')
    op.drop_index(op.f('ix_equipamentos_id'), table_name='equipamentos')
    op.drop_table('equipamentos')
    op.drop_index(op.f('ix_representacoes_b2b_id'), table_name='representacoes_b2b')
    op.drop_index(op.f('ix_representacoes_b2b_cnpj_cliente_final'), table_name='representacoes_b2b')
    op.drop_table('representacoes_b2b')
    op.drop_index(op.f('ix_enderecos_id'), table_name='enderecos')
    op.drop_table('enderecos')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_index(op.f('ix_documentos_kyc_id'), table_name='documentos_kyc')
    op.drop_table('documentos_kyc')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_documento'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
