"""Criando tabela de vistorias logisticas

Revision ID: d952db3756d7
Revises: 85c861ad3ecf
Create Date: 2026-03-23 14:30:54.523136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd952db3756d7'
down_revision: Union[str, Sequence[str], None] = '85c861ad3ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vistorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locacao_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTREGA', 'DEVOLUCAO', name='tipovistoria'), nullable=False),
    sa.Column('data_vistoria', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('assinatura_cliente_url', sa.String(), nullable=True),
    sa.Column('fotos_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['locacao_id'], ['locacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vistorias_id'), 'vistorias', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vistorias_id'), table_name='vistorias')
    op.drop_table('vistorias')
    # ### end Alembic commands ###
