"""Criando tabela de equipamentos universal

Revision ID: f218d72edfdd
Revises: c98778f28747
Create Date: 2026-03-23 01:19:03.899259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f218d72edfdd'
down_revision: Union[str, Sequence[str], None] = 'c98778f28747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('numero_serie_patrimonio', sa.String(), nullable=True),
    sa.Column('valor_base_locacao', sa.Float(), nullable=False),
    sa.Column('tipo_cobranca', sa.Enum('DIARIA', 'MENSAL', 'HORA', 'FRANQUIA', name='tipocobranca'), nullable=True),
    sa.Column('categoria', sa.Enum('LINHA_PESADA', 'LINHA_LEVE', 'VEICULOS', 'MENSALISTAS', 'DIVERSOS', name='categoriaequipamento'), nullable=True),
    sa.Column('quantidade_total', sa.Integer(), nullable=True),
    sa.Column('quantidade_disponivel', sa.Integer(), nullable=True),
    sa.Column('em_manutencao', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipamentos_id'), 'equipamentos', ['id'], unique=False)
    op.create_index(op.f('ix_equipamentos_nome'), 'equipamentos', ['nome'], unique=False)
    op.create_index(op.f('ix_equipamentos_numero_serie_patrimonio'), 'equipamentos', ['numero_serie_patrimonio'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipamentos_numero_serie_patrimonio'), table_name='equipamentos')
    op.drop_index(op.f('ix_equipamentos_nome'), table_name='equipamentos')
    op.drop_index(op.f('ix_equipamentos_id'), table_name='equipamentos')
    op.drop_table('equipamentos')
    # ### end Alembic commands ###
